# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- script: |
    VM_IP=$(az vm show \
      --resource-group terraform-learning-rg2 \
      --name sweb-vm \
      --show-details \
      --query publicIps \
      --output tsv)

    echo "VM IP: $VM_IP"

    cat > ansible/inventory.ini <<EOF
    [web]
    sweb-vm ansible_host=$VM_IP ansible_user=azureuser
    EOF
  displayName: "Generate Ansible Inventory"

- task: JavaToolInstaller@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled

- script: |
    cd webApplication
    chmod +x gradlew
    ./gradlew clean test bootJar
  displayName: "Build Spring Boot"

- task: Docker@2
  displayName: "Build and Push Docker Image"
  inputs:
    command: buildAndPush
    containerRegistry: "docker-terraform-learning-sc"
    repository: myapp
    Dockerfile: webApplication/Dockerfile
    buildContext: webApplication
    tags: |
      latest
      $(Build.BuildId)
- task: DownloadSecureFile@1
  name: sshKey
  displayName: "Download SSH private key"
  inputs:
    secureFile: id_rsa

- script: |
    chmod 600 "$(sshKey.secureFilePath)"
  displayName: "Set SSH key permissions"

- task: AzureCLI@2
  displayName: "Get VM Public IP"
  inputs:
    azureSubscription: "terraform-learning-rg"
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -e

      VM_IP=$(az network public-ip show \
        --resource-group terraform-learning-rg2 \
        --name web-public-ip \
        --query ipAddress \
        --output tsv)

      echo "VM_IP=[$VM_IP]"

      if [ -z "$VM_IP" ]; then
        echo "ERROR: VM_IP is empty"
        exit 1
      fi

      cat > ansible/inventory.ini <<EOF
      [web]
      sweb-vm ansible_host=$VM_IP ansible_user=azureuser ansible_ssh_private_key_file=$(sshKey.secureFilePath)
      EOF
      
      cat ansible/inventory.ini

- script: |
    python3 -m pip install --user ansible
    ansible-galaxy collection install community.docker
  displayName: "Install Ansible"

- script: |
    ansible web \
      -i ansible/inventory.ini \
      -m ping
  displayName: "Test Ansible SSH"

#- task: SSH@0
#  inputs:
#    sshEndpoint: vm-ssh
#    displayName: "Deploy Docker Image"
#    runOptions: inline
#    inline: |
#      az login --identity
#      az acr login --name xiaolinterraformacr01
#      docker pull xiaolinterraformacr01.azurecr.io/myapp:$(Build.BuildId)
#
#      DB_PASSWORD=$(az keyvault secret show \
#      --vault-name xlli-learning-kv \
#      --name db-password \
#      --query value -o tsv)
#
#      if docker ps -a --format '{{.Names}}' | grep -qx "myapp"; then
#        docker stop myapp
#        docker rm myapp
#      fi
#      docker run -d \
#      --restart always \
#      --name myapp \
#      -p 8080:8080 \
#      -e SPRING_DATASOURCE_USERNAME="postgresadmin" \
#      -e SPRING_DATASOURCE_PASSWORD="$DB_PASSWORD" \
#      -e DB_HOST="xlli-learning-postgres.postgres.database.azure.com" \
#      -e DB_PORT="5432" \
#      -e DB_NAME="myapp" \
#      xiaolinterraformacr01.azurecr.io/myapp:$(Build.BuildId)